

echo " "
    echo -e "$Red                                 ⫸ Base:$Yellow faizan$Red ⫷\033[0m"
    echo -e "$Red                               ⫸$Purple WeCry x M4T01$Red ⫷\033[0m"
    echo -e "$Red                                 ⫸ List by $Yellow m4t01$Red ⫷\033[0m"
echo " "
echo -e " $Green     |---------------------------------------------------------------------|"
echo -e " $Green     ||----------------------------$Cyan [List] $Green---------------------------||"
echo -e " $Green     ||                                                                   "
echo -e " $Green     ||             $Purple==>$Yellow[1] IG information gathering$Green                    "
echo -e " $Green     ||             $Purple==>️$Yellow[2] IG brute force attack$Green                       "
echo -e " $Green     ||             $Purple==>$Yellow[3] IG auto reporter$Green                            "
echo -e " $Green     ||             $Purple==>$Yellow[4] IG phishing ( soon)$Green               "
echo -e " $Green     ||             $Purple==>$Yellow[5] Telegram Links$Green                                  "
echo -e " $Green     ||             $Purple==>$Yellow[6] Remove scripts$Green                                  "
echo -e " $Green     ||             $Purple==>$Yellow[7] About$Green                                          "
echo -e " $Green     ||             $Purple==>$Yellow[8] exit$Green                                           "
echo -e " $Green     ||             $Purple==>$Yellow[9] Venom Tool (370+)$Green                                        "
echo -e " $Green     ||             $Purple==>$Yellow[999] Reset/Update Tool$Green                                           "
echo -e " $Green     ||                                                                   "                                                                                       
echo -e " $Green     ||---------------------------$Cyan [select option] $Green-----------------------||"
echo -e " $Green     |---------------------------------------------------------------------|"
echo " "
